# Generated by Django 4.1.7 on 2023-03-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "food"),
                    ("health", "health"),
                    ("housing", "housing"),
                    ("transportation", "transportation"),
                    ("education", "education"),
                    ("leisure", "leisure"),
                    ("unforeseen", "unforeseen"),
                    ("other", "other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
